# Spring properties
spring:
  application:
     name: shopping-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

# wavefront
wavefront:
  application:
    name: SpringShirts