# Spring properties
spring:
  application:
     name: styling-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

# wavefront
wavefront:
  application:
    name: SpringShirts