# Reporting through direct ingestion
reportingMechanism: "direct"
server: "https://<YOUR WAVEFRONT SERVER>.wavefront.com"
token: "<YOUR WAVEFRONT API TOKEN>"
source: "wavefront-tracing-example"
reportTraces: true
